# SPDX-License-Identifier: GPL-2.0

load("//vendor/amlogic/kernel:kernel_platform.bzl", "amlogic_kernel_platform")
load("//vendor/amlogic/gpu-modules/bifrost:defs.bzl", "mali_bifrost_module")
load("//vendor/amlogic/media-modules:defs.bzl", "media_modules_module")
load(":modules.bzl", "COMMON_DRIVERS_MODULES", "GKI_MODULES_REMOVE", "OHM_MODULES", "MODULES_OUT_REMOVE", "SYSTEM_DLKM_MODULES")

package(
    default_visibility = ["//visibility:public"],
)

mali_bifrost_module(name = "gpu_bifrost", kernel_build = ":ohm")

media_modules_module(name = "media", kernel_build = ":ohm")

amlogic_kernel_platform(
    name = "ohm",
    dtb_outs = [
        "sc2_s905x4_ah212_drm.dtb",
        "android_overlay_dt.dtbo",
    ],
    module_outs = [m for m in OHM_MODULES + COMMON_DRIVERS_MODULES + SYSTEM_DLKM_MODULES if m not in MODULES_OUT_REMOVE],
    gki_modules_remove = GKI_MODULES_REMOVE + SYSTEM_DLKM_MODULES,
    system_dlkm_modules_load = ["kernel/" + m for m in SYSTEM_DLKM_MODULES] + [""],
    build_config = "//vendor/amlogic/kernel:build.config.ohm.bazel",
    kmi_symbol_list = "//vendor/amlogic/kernel:android/abi_gki_aarch64_amlogic",
    kernel_modules = [
        ":wlan_ap6356",
        ":gpu_bifrost",
        ":media",
    ],
)
